### Obtener películas
GET http://localhost:1234/movies

### Obtener una película
GET http://localhost:1234/movies/2a1c57e9-fa0c-11f0-ac87-26893c942f31

### Obtener películas según género
GET http://localhost:1234/movies?genre=ACTION

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Gladiator",
  "year": 2000,
  "director": "Ridley Scott",
  "duration": 155,
  "poster": "https://img.fruugo.com/product/0/60/14417600_max.jpg",
  "genre": ["Action", "Adventure", "Drama"],
  "rate": 8.5
}

### Actualizar una película
PATCH http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
Content-Type: application/json

{
    "year": 2008
}


### Eliminar una pelicula
DELETE http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf