DROP DATABASE IF EXISTS ordena;
CREATE DATABASE IF NOT EXISTS ordena;

USE ordena;

CREATE TABLE IF NOT EXISTS TBL_USERS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    dni VARCHAR(30) NOT NULL,
    typeDocument ENUM("CEDULA DE CIUDADANIA", "CEDULA DE EXTRANJERIA", "PASAPORTE", "NIT", "TARJETA DE IDENTIDAD"),
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(13) NOT NULL,
    role ENUM("ADMINISTRADOR", "MESERO", "COCINERO", "CLIENTE") NOT NULL,
    nationality VARCHAR(30),
    image TEXT,
    active BOOLEAN DEFAULT TRUE,
    birthdate DATE NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS TBL_CLIENTS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(13),
    nationality VARCHAR(30),
    image TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS TBL_PRODUCTS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    availability BOOLEAN DEFAULT TRUE,
    price DECIMAL(10,2) NOT NULL,
    image TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);


CREATE TABLE IF NOT EXISTS TBL_TABLES(
    id INT AUTO_INCREMENT PRIMARY KEY,
    number INT UNIQUE NOT NULL,
    capacity INT NOT NULL,
    state ENUM("LIBRE", "OCUPADA", "RESERVADA") DEFAULT "LIBRE"
);


CREATE TABLE IF NOT EXISTS TBL_ORDERS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    state ENUM("PENDIENTE", "EN PREPARACION", "LISTO", "ENTREGADO", "FACTURADO") DEFAULT "PENDIENTE",
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    table_number INT NOT NULL,
    client_id INT,
    user_id INT NOT NULL,

    FOREIGN KEY (table_number) REFERENCES TBL_TABLES(number),
    FOREIGN KEY (client_id) REFERENCES TBL_CLIENTS(id),
    FOREIGN KEY (user_id) REFERENCES TBL_USERS(id)
);


CREATE TABLE IF NOT EXISTS TBL_BILLS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total DECIMAL(10,2) NOT NULL,
    order_id INT NOT NULL,
    user_id INT NOT NULL,
    client_id INT,

    FOREIGN KEY (order_id) REFERENCES TBL_ORDERS(id),
    FOREIGN KEY (user_id) REFERENCES TBL_USERS(id),
    FOREIGN KEY (client_id) REFERENCES TBL_CLIENTS(id)
);


CREATE TABLE IF NOT EXISTS TBL_ORDER_PRODUCTS(
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    price DECIMAL (10,2) NOT NULL,

    PRIMARY KEY(order_id, product_id),

    FOREIGN KEY (order_id) REFERENCES TBL_ORDERS(id),
    FOREIGN KEY (product_id) REFERENCES TBL_PRODUCTS(id)
);